apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-deployment      # Nama Deployment yang mau di-autoscale
  minReplicas: 1                 # Minimum Pod
  maxReplicas: 10                # Maksimum Pod
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 # Kalau rata-rata CPU > 50%, tambah Pod
